services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-stable
      - app-canary

  app-stable:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VERSION=1.0.0
      - BG_COLOR=#3498db
      - STATUS=STABLE

  app-canary:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VERSION=2.0.0
      - BG_COLOR=#e74c3c
      - STATUS=CANARY